// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 2.4.7.
// **********************************************************************

#ifndef __BASEF_H_
#define __BASEF_H_

#include <map>
#include <string>
#include <vector>
#include "client/protocol/Tars.h"

using namespace std;


namespace horsedb
{
    const horsedb::Short TARSVERSION = 1;

    const horsedb::Short TUPVERSION = 3;

    const horsedb::Short XMLVERSION = 4;

    const horsedb::Short JSONVERSION = 5;

    const horsedb::Char TARSNORMAL = 0;

    const horsedb::Char TARSONEWAY = 1;

    const horsedb::Int32 TARSSERVERSUCCESS = 0;

    const horsedb::Int32 TARSSERVERDECODEERR = -1;

    const horsedb::Int32 TARSSERVERENCODEERR = -2;

    const horsedb::Int32 TARSSERVERNOFUNCERR = -3;

    const horsedb::Int32 TARSSERVERNOSERVANTERR = -4;

    const horsedb::Int32 TARSSERVERRESETGRID = -5;

    const horsedb::Int32 TARSSERVERQUEUETIMEOUT = -6;

    const horsedb::Int32 TARSASYNCCALLTIMEOUT = -7;

    const horsedb::Int32 TARSINVOKETIMEOUT = -7;

    const horsedb::Int32 TARSPROXYCONNECTERR = -8;

    const horsedb::Int32 TARSSERVEROVERLOAD = -9;

    const horsedb::Int32 TARSADAPTERNULL = -10;

    const horsedb::Int32 TARSINVOKEBYINVALIDESET = -11;

    const horsedb::Int32 TARSCLIENTDECODEERR = -12;

    const horsedb::Int32 TARSSERVERUNKNOWNERR = -99;

    const horsedb::Int32 TARSMESSAGETYPENULL = 0;

    const horsedb::Int32 TARSMESSAGETYPEHASH = 1;

    const horsedb::Int32 TARSMESSAGETYPEGRID = 2;

    const horsedb::Int32 TARSMESSAGETYPEDYED = 4;

    const horsedb::Int32 TARSMESSAGETYPESAMPLE = 8;

    const horsedb::Int32 TARSMESSAGETYPEASYNC = 16;

    const horsedb::Int32 TARSMESSAGETYPESETNAME = 128;

    const horsedb::Int32 TARSMESSAGETYPETRACK = 256;


}



#endif
